#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-mime-types
Version  : 2.6.1
Release  : 7
URL      : https://rubygems.org/downloads/mime-types-2.6.1.gem
Source0  : https://rubygems.org/downloads/mime-types-2.6.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-minitest-focus
BuildRequires : rubygem-rdoc

%description
= mime-types
home :: https://github.com/mime-types/ruby-mime-types/
code :: https://github.com/mime-types/ruby-mime-types/
bugs :: https://github.com/mime-types/ruby-mime-types/issues
rdoc :: http://rdoc.info/gems/mime-types/
continuous integration :: {<img src="https://travis-ci.org/mime-types/ruby-mime-types.png" />}[https://travis-ci.org/mime-types/ruby-mime-types]
test coverage :: {<img src="https://coveralls.io/repos/mime-types/ruby-mime-types/badge.png" alt="Coverage Status" />}[https://coveralls.io/r/mime-types/ruby-mime-types]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n mime-types-2.6.1
gem spec %{SOURCE0} -l --ruby > rubygem-mime-types.gemspec

%build
gem build rubygem-mime-types.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
mime-types-2.6.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
pushd %{buildroot}%{gem_dir}/gems/mime-types-2.6.1
ruby -I"lib:test" test/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/mime-types-2.6.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/Columnar/cdesc-Columnar.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/InvalidContentType/cdesc-InvalidContentType.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/InvalidEncoding/cdesc-InvalidEncoding.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/add_extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/ascii%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/binary%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/cdesc-Type.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/complete%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/content_type%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/content_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/default_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/docs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/encode_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/friendly-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/from_array-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/from_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/from_mime_type-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/i18n_key-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/i18n_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/init_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/like%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/media_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/obsolete%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/platform%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/preferred_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/priority_compare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/raw_media_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/raw_sub_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/references-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/registered%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/signature%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/simplified-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/simplified-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/sub_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/system%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/to_h-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/urls-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/use_instead-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/xref_urls-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Type/xrefs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/%5b%5d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Cache/cdesc-Cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Cache/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Cache/save-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/arr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/bool-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/cdesc-Columnar.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/dict-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/each_file_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_docs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_friendly-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_obsolete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_references-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_registered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_signature-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_use_instead-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Columnar/load_xrefs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Container/cdesc-Container.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/cdesc-Loader.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/columnar_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/container-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/json_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load_columnar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load_from_json-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load_from_v1-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load_from_yaml-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load_v1-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/load_yaml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/read_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/v1_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/Loader/yaml_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/WarnLogger/WarnLogDevice/cdesc-WarnLogDevice.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/WarnLogger/cdesc-WarnLogger.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/__types__-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/add-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/add_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/add_type_variant%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/cache_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/cdesc-Types.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/count-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/data_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/each-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/index_extensions%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/lazy_load%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/load_default_mime_types-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/load_from_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/load_mode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/logger-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/of-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/prune_matches-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/type_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/Types/type_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/cdesc-MIME.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/MIME/warn_about_moved_constants-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/docs/page-COPYING_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/docs/page-artistic_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/page-Contributing_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/page-History-Types_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/page-History_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/page-Licence_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/mime-types-2.6.1/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/.hoerc
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/Contributing.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/History-Types.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/History.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/Licence.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime-types.json
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.content_type.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.docs.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.encoding.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.friendly.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.obsolete.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.references.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.registered.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.signature.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.system.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.use_instead.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/data/mime.xrefs.column
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/docs/COPYING.txt
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/docs/artistic.txt
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime-types.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/type.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/type/columnar.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/types.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/types/cache.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/types/columnar.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/types/deprecations.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/types/loader.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/types/loader_path.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib/mime/types/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/support/apache_mime_types.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/support/benchmarks/load.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/support/benchmarks/load_allocations.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/support/benchmarks/object_counts.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/support/convert.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/support/convert/columnar.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/support/iana_registry.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/bad-fixtures/malformed
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/fixture/json.json
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/fixture/old-data
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/fixture/yaml.yaml
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/minitest_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/test_mime_type.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/test_mime_types.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/test_mime_types_cache.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/test_mime_types_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/test_mime_types_lazy.rb
/usr/lib64/ruby/gems/2.2.0/gems/mime-types-2.6.1/test/test_mime_types_loader.rb
/usr/lib64/ruby/gems/2.2.0/specifications/mime-types-2.6.1.gemspec
